apiVersion: v1
kind: Service
metadata:
  name: overleaf
  namespace: kovacovsky-ns
  labels:
    app.kubernetes.io/name: overleaf
    app.kubernetes.io/part-of: overleaf
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: web-api
      port: 3000
      targetPort: 3000
    - name: history-v1
      port: 3100
      targetPort: 3100
  selector:
    app.kubernetes.io/name: overleaf
